steps:
  - label: ":sparkles: Tests"
    plugins:
      - plugin-tester#v1.3.0: ~

  - label: ":lint-roller: Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: buildkite/setup-go

  - label: ":golang: Smoke test"
    command:
      - "command -v go"
      - "go version"
      - "go env -json GOVERSION GOROOT GOPATH GOMODCACHE GOCACHE GOBIN"
      - "command -v shellcheck"
      - "shellcheck --version"
      - "shellcheck hooks/pre-command tests/pre-command.bats"
    plugins:
      - buildkite/mise#v1.1.0: ~
      - ./: 
          version: 1.24.0

  - label: ":shell: Shellcheck"
    command: shellcheck hooks/* tests/pre-command.bats
    plugins:
      - buildkite/mise#v1.1.0: ~
